# Generated by Django 6.0 on 2025-12-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Professor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Professor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
