# Generated by Django 6.0 on 2025-12-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_banner_evento_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
