# Generated by Django 6.0 on 2025-12-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_vagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(),
        ),
    ]
