# Generated by Django 6.0 on 2025-12-15 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='certificado',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
