# Generated by Django 6.0 on 2025-12-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ORGANIZADOR', 'Organizador')], default='ALUNO', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
